debug:
  enabled: false
fuscation-mode: CHUNK_AND_BLOCK
async:
# Workers threads to use. 0 means async is disabled, and everything will run on main thread. Should be max equal to core thread of system.
  worker-count: 0
preferred-obfuscation-material: 'minecraft:end_stone'
hidden:
  block:
    entities:
    filter: